# Generated by Django 5.2.7 on 2025-10-23 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('sandwich', 'Sandwich'), ('ensalada', 'Ensalada'), ('bebida', 'Bebida'), ('snack', 'Snack'), ('postre', 'Postre')], max_length=20)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('calorias', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'productos',
            },
        ),
    ]
